//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/DocufloSDK/Service1", ItemName="string")]
    public class ArrayOfString : System.Collections.Generic.List<string>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataProfileResult", Namespace="http://tempuri.org/DocufloSDK/Service1")]
    public partial class DataProfileResult : object
    {
        
        private ServiceReference.DataColumn[] Arr_DataValueField;
        
        private long VerIDField;
        
        private long ProfileIDField;
        
        private long DocIDField;
        
        private string ImageNameField;
        
        private int TotalRecFoundField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ServiceReference.DataColumn[] Arr_DataValue
        {
            get
            {
                return this.Arr_DataValueField;
            }
            set
            {
                this.Arr_DataValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long VerID
        {
            get
            {
                return this.VerIDField;
            }
            set
            {
                this.VerIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public long ProfileID
        {
            get
            {
                return this.ProfileIDField;
            }
            set
            {
                this.ProfileIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public long DocID
        {
            get
            {
                return this.DocIDField;
            }
            set
            {
                this.DocIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ImageName
        {
            get
            {
                return this.ImageNameField;
            }
            set
            {
                this.ImageNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int TotalRecFound
        {
            get
            {
                return this.TotalRecFoundField;
            }
            set
            {
                this.TotalRecFoundField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataColumn", Namespace="http://tempuri.org/DocufloSDK/Service1")]
    public partial class DataColumn : object
    {
        
        private string Col_DescField;
        
        private string ProfileValueField;
        
        private string Col_IDField;
        
        private string Col_NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Col_Desc
        {
            get
            {
                return this.Col_DescField;
            }
            set
            {
                this.Col_DescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ProfileValue
        {
            get
            {
                return this.ProfileValueField;
            }
            set
            {
                this.ProfileValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Col_ID
        {
            get
            {
                return this.Col_IDField;
            }
            set
            {
                this.Col_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Col_Name
        {
            get
            {
                return this.Col_NameField;
            }
            set
            {
                this.Col_NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType", Namespace="http://tempuri.org/DocufloSDK/Service1", ItemName="anyType")]
    public class ArrayOfAnyType : System.Collections.Generic.List<object>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Profiles", Namespace="http://tempuri.org/DocufloSDK/Service1")]
    public partial class Profiles : object
    {
        
        private int profileIDField;
        
        private string profileNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int profileID
        {
            get
            {
                return this.profileIDField;
            }
            set
            {
                this.profileIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string profileName
        {
            get
            {
                return this.profileNameField;
            }
            set
            {
                this.profileNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProfileField", Namespace="http://tempuri.org/DocufloSDK/Service1")]
    public partial class ProfileField : object
    {
        
        private int colIDField;
        
        private string colNameField;
        
        private string colDescField;
        
        private string colDataTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int colID
        {
            get
            {
                return this.colIDField;
            }
            set
            {
                this.colIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string colName
        {
            get
            {
                return this.colNameField;
            }
            set
            {
                this.colNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string colDesc
        {
            get
            {
                return this.colDescField;
            }
            set
            {
                this.colDescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string colDataType
        {
            get
            {
                return this.colDataTypeField;
            }
            set
            {
                this.colDataTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org/DocufloSDK/Service1", ConfigurationName="ServiceReference.DocufloSDKSoap")]
    public interface DocufloSDKSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DocufloSDK/Service1/Export", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.ExportResponse> ExportAsync(ServiceReference.ExportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DocufloSDK/Service1/Search", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.SearchResponse> SearchAsync(ServiceReference.SearchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DocufloSDK/Service1/SearchByDocID", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.SearchByDocIDResponse> SearchByDocIDAsync(ServiceReference.SearchByDocIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DocufloSDK/Service1/ProfileSearch", ReplyAction="*")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceReference.ArrayOfString))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceReference.DataProfileResult[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceReference.DataProfileResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceReference.DataColumn[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceReference.DataColumn))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceReference.ArrayOfAnyType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceReference.Profiles))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceReference.Profiles[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceReference.ProfileField))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceReference.ProfileField[]))]
        System.Threading.Tasks.Task<ServiceReference.ProfileSearchResponse> ProfileSearchAsync(ServiceReference.ProfileSearchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DocufloSDK/Service1/Download", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.DownloadResponse> DownloadAsync(ServiceReference.DownloadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DocufloSDK/Service1/UpdateTargetProfileValue", ReplyAction="*")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceReference.ArrayOfString))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceReference.DataProfileResult[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceReference.DataProfileResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceReference.DataColumn[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceReference.DataColumn))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceReference.ArrayOfAnyType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceReference.Profiles))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceReference.Profiles[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceReference.ProfileField))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceReference.ProfileField[]))]
        System.Threading.Tasks.Task<ServiceReference.UpdateTargetProfileValueResponse> UpdateTargetProfileValueAsync(ServiceReference.UpdateTargetProfileValueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DocufloSDK/Service1/DeleteDocument", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.DeleteDocumentResponse> DeleteDocumentAsync(ServiceReference.DeleteDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DocufloSDK/Service1/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.LoginResponse> LoginAsync(ServiceReference.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DocufloSDK/Service1/LoadProfiles", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.LoadProfilesResponse> LoadProfilesAsync(ServiceReference.LoadProfilesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DocufloSDK/Service1/LoadProfileField", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.LoadProfileFieldResponse> LoadProfileFieldAsync(ServiceReference.LoadProfileFieldRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExportRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Export", Namespace="http://tempuri.org/DocufloSDK/Service1", Order=0)]
        public ServiceReference.ExportRequestBody Body;
        
        public ExportRequest()
        {
        }
        
        public ExportRequest(ServiceReference.ExportRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/DocufloSDK/Service1")]
    public partial class ExportRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] FileContent;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strFileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strProfile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string strFolderName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public ServiceReference.ArrayOfString arrProfileValue;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string userID;
        
        public ExportRequestBody()
        {
        }
        
        public ExportRequestBody(byte[] FileContent, string strFileName, string strProfile, string strFolderName, ServiceReference.ArrayOfString arrProfileValue, string userID)
        {
            this.FileContent = FileContent;
            this.strFileName = strFileName;
            this.strProfile = strProfile;
            this.strFolderName = strFolderName;
            this.arrProfileValue = arrProfileValue;
            this.userID = userID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExportResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExportResponse", Namespace="http://tempuri.org/DocufloSDK/Service1", Order=0)]
        public ServiceReference.ExportResponseBody Body;
        
        public ExportResponse()
        {
        }
        
        public ExportResponse(ServiceReference.ExportResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/DocufloSDK/Service1")]
    public partial class ExportResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ExportResult;
        
        public ExportResponseBody()
        {
        }
        
        public ExportResponseBody(string ExportResult)
        {
            this.ExportResult = ExportResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Search", Namespace="http://tempuri.org/DocufloSDK/Service1", Order=0)]
        public ServiceReference.SearchRequestBody Body;
        
        public SearchRequest()
        {
        }
        
        public SearchRequest(ServiceReference.SearchRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/DocufloSDK/Service1")]
    public partial class SearchRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strCriteria;
        
        public SearchRequestBody()
        {
        }
        
        public SearchRequestBody(string strCriteria)
        {
            this.strCriteria = strCriteria;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchResponse", Namespace="http://tempuri.org/DocufloSDK/Service1", Order=0)]
        public ServiceReference.SearchResponseBody Body;
        
        public SearchResponse()
        {
        }
        
        public SearchResponse(ServiceReference.SearchResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/DocufloSDK/Service1")]
    public partial class SearchResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference.DataProfileResult[] SearchResult;
        
        public SearchResponseBody()
        {
        }
        
        public SearchResponseBody(ServiceReference.DataProfileResult[] SearchResult)
        {
            this.SearchResult = SearchResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchByDocIDRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchByDocID", Namespace="http://tempuri.org/DocufloSDK/Service1", Order=0)]
        public ServiceReference.SearchByDocIDRequestBody Body;
        
        public SearchByDocIDRequest()
        {
        }
        
        public SearchByDocIDRequest(ServiceReference.SearchByDocIDRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/DocufloSDK/Service1")]
    public partial class SearchByDocIDRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int profileID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long docID;
        
        public SearchByDocIDRequestBody()
        {
        }
        
        public SearchByDocIDRequestBody(int profileID, long docID)
        {
            this.profileID = profileID;
            this.docID = docID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchByDocIDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchByDocIDResponse", Namespace="http://tempuri.org/DocufloSDK/Service1", Order=0)]
        public ServiceReference.SearchByDocIDResponseBody Body;
        
        public SearchByDocIDResponse()
        {
        }
        
        public SearchByDocIDResponse(ServiceReference.SearchByDocIDResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/DocufloSDK/Service1")]
    public partial class SearchByDocIDResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference.DataProfileResult[] SearchByDocIDResult;
        
        public SearchByDocIDResponseBody()
        {
        }
        
        public SearchByDocIDResponseBody(ServiceReference.DataProfileResult[] SearchByDocIDResult)
        {
            this.SearchByDocIDResult = SearchByDocIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProfileSearchRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProfileSearch", Namespace="http://tempuri.org/DocufloSDK/Service1", Order=0)]
        public ServiceReference.ProfileSearchRequestBody Body;
        
        public ProfileSearchRequest()
        {
        }
        
        public ProfileSearchRequest(ServiceReference.ProfileSearchRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/DocufloSDK/Service1")]
    public partial class ProfileSearchRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string profile_name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ServiceReference.ArrayOfAnyType column_names;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ServiceReference.ArrayOfAnyType column_keywords;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string error_msg;
        
        public ProfileSearchRequestBody()
        {
        }
        
        public ProfileSearchRequestBody(string profile_name, ServiceReference.ArrayOfAnyType column_names, ServiceReference.ArrayOfAnyType column_keywords, string error_msg)
        {
            this.profile_name = profile_name;
            this.column_names = column_names;
            this.column_keywords = column_keywords;
            this.error_msg = error_msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProfileSearchResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProfileSearchResponse", Namespace="http://tempuri.org/DocufloSDK/Service1", Order=0)]
        public ServiceReference.ProfileSearchResponseBody Body;
        
        public ProfileSearchResponse()
        {
        }
        
        public ProfileSearchResponse(ServiceReference.ProfileSearchResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/DocufloSDK/Service1")]
    public partial class ProfileSearchResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference.DataProfileResult[] ProfileSearchResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string error_msg;
        
        public ProfileSearchResponseBody()
        {
        }
        
        public ProfileSearchResponseBody(ServiceReference.DataProfileResult[] ProfileSearchResult, string error_msg)
        {
            this.ProfileSearchResult = ProfileSearchResult;
            this.error_msg = error_msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Download", Namespace="http://tempuri.org/DocufloSDK/Service1", Order=0)]
        public ServiceReference.DownloadRequestBody Body;
        
        public DownloadRequest()
        {
        }
        
        public DownloadRequest(ServiceReference.DownloadRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/DocufloSDK/Service1")]
    public partial class DownloadRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long VerID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long DocProfileID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public short FileType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string FileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public byte[] FileContent;
        
        public DownloadRequestBody()
        {
        }
        
        public DownloadRequestBody(long VerID, long DocProfileID, short FileType, string FileName, byte[] FileContent)
        {
            this.VerID = VerID;
            this.DocProfileID = DocProfileID;
            this.FileType = FileType;
            this.FileName = FileName;
            this.FileContent = FileContent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownloadResponse", Namespace="http://tempuri.org/DocufloSDK/Service1", Order=0)]
        public ServiceReference.DownloadResponseBody Body;
        
        public DownloadResponse()
        {
        }
        
        public DownloadResponse(ServiceReference.DownloadResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/DocufloSDK/Service1")]
    public partial class DownloadResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DownloadResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] FileContent;
        
        public DownloadResponseBody()
        {
        }
        
        public DownloadResponseBody(string DownloadResult, string FileName, byte[] FileContent)
        {
            this.DownloadResult = DownloadResult;
            this.FileName = FileName;
            this.FileContent = FileContent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateTargetProfileValueRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateTargetProfileValue", Namespace="http://tempuri.org/DocufloSDK/Service1", Order=0)]
        public ServiceReference.UpdateTargetProfileValueRequestBody Body;
        
        public UpdateTargetProfileValueRequest()
        {
        }
        
        public UpdateTargetProfileValueRequest(ServiceReference.UpdateTargetProfileValueRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/DocufloSDK/Service1")]
    public partial class UpdateTargetProfileValueRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long docID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string profile_name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string base_column_name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public object base_value;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string target_column_name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public object target_value;
        
        public UpdateTargetProfileValueRequestBody()
        {
        }
        
        public UpdateTargetProfileValueRequestBody(long docID, string profile_name, string base_column_name, object base_value, string target_column_name, object target_value)
        {
            this.docID = docID;
            this.profile_name = profile_name;
            this.base_column_name = base_column_name;
            this.base_value = base_value;
            this.target_column_name = target_column_name;
            this.target_value = target_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateTargetProfileValueResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateTargetProfileValueResponse", Namespace="http://tempuri.org/DocufloSDK/Service1", Order=0)]
        public ServiceReference.UpdateTargetProfileValueResponseBody Body;
        
        public UpdateTargetProfileValueResponse()
        {
        }
        
        public UpdateTargetProfileValueResponse(ServiceReference.UpdateTargetProfileValueResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/DocufloSDK/Service1")]
    public partial class UpdateTargetProfileValueResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateTargetProfileValueResult;
        
        public UpdateTargetProfileValueResponseBody()
        {
        }
        
        public UpdateTargetProfileValueResponseBody(string UpdateTargetProfileValueResult)
        {
            this.UpdateTargetProfileValueResult = UpdateTargetProfileValueResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteDocumentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteDocument", Namespace="http://tempuri.org/DocufloSDK/Service1", Order=0)]
        public ServiceReference.DeleteDocumentRequestBody Body;
        
        public DeleteDocumentRequest()
        {
        }
        
        public DeleteDocumentRequest(ServiceReference.DeleteDocumentRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/DocufloSDK/Service1")]
    public partial class DeleteDocumentRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long docID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long profileID;
        
        public DeleteDocumentRequestBody()
        {
        }
        
        public DeleteDocumentRequestBody(long docID, long profileID)
        {
            this.docID = docID;
            this.profileID = profileID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteDocumentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteDocumentResponse", Namespace="http://tempuri.org/DocufloSDK/Service1", Order=0)]
        public ServiceReference.DeleteDocumentResponseBody Body;
        
        public DeleteDocumentResponse()
        {
        }
        
        public DeleteDocumentResponse(ServiceReference.DeleteDocumentResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/DocufloSDK/Service1")]
    public partial class DeleteDocumentResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteDocumentResult;
        
        public DeleteDocumentResponseBody()
        {
        }
        
        public DeleteDocumentResponseBody(string DeleteDocumentResult)
        {
            this.DeleteDocumentResult = DeleteDocumentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/DocufloSDK/Service1", Order=0)]
        public ServiceReference.LoginRequestBody Body;
        
        public LoginRequest()
        {
        }
        
        public LoginRequest(ServiceReference.LoginRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/DocufloSDK/Service1")]
    public partial class LoginRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userID;
        
        public LoginRequestBody()
        {
        }
        
        public LoginRequestBody(string userName, string userPassword, string userID)
        {
            this.userName = userName;
            this.userPassword = userPassword;
            this.userID = userID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/DocufloSDK/Service1", Order=0)]
        public ServiceReference.LoginResponseBody Body;
        
        public LoginResponse()
        {
        }
        
        public LoginResponse(ServiceReference.LoginResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/DocufloSDK/Service1")]
    public partial class LoginResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoginResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userID;
        
        public LoginResponseBody()
        {
        }
        
        public LoginResponseBody(string LoginResult, string userID)
        {
            this.LoginResult = LoginResult;
            this.userID = userID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadProfilesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadProfiles", Namespace="http://tempuri.org/DocufloSDK/Service1", Order=0)]
        public ServiceReference.LoadProfilesRequestBody Body;
        
        public LoadProfilesRequest()
        {
        }
        
        public LoadProfilesRequest(ServiceReference.LoadProfilesRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class LoadProfilesRequestBody
    {
        
        public LoadProfilesRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadProfilesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadProfilesResponse", Namespace="http://tempuri.org/DocufloSDK/Service1", Order=0)]
        public ServiceReference.LoadProfilesResponseBody Body;
        
        public LoadProfilesResponse()
        {
        }
        
        public LoadProfilesResponse(ServiceReference.LoadProfilesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/DocufloSDK/Service1")]
    public partial class LoadProfilesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference.Profiles[] LoadProfilesResult;
        
        public LoadProfilesResponseBody()
        {
        }
        
        public LoadProfilesResponseBody(ServiceReference.Profiles[] LoadProfilesResult)
        {
            this.LoadProfilesResult = LoadProfilesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadProfileFieldRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadProfileField", Namespace="http://tempuri.org/DocufloSDK/Service1", Order=0)]
        public ServiceReference.LoadProfileFieldRequestBody Body;
        
        public LoadProfileFieldRequest()
        {
        }
        
        public LoadProfileFieldRequest(ServiceReference.LoadProfileFieldRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/DocufloSDK/Service1")]
    public partial class LoadProfileFieldRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int intProfileID;
        
        public LoadProfileFieldRequestBody()
        {
        }
        
        public LoadProfileFieldRequestBody(int intProfileID)
        {
            this.intProfileID = intProfileID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadProfileFieldResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadProfileFieldResponse", Namespace="http://tempuri.org/DocufloSDK/Service1", Order=0)]
        public ServiceReference.LoadProfileFieldResponseBody Body;
        
        public LoadProfileFieldResponse()
        {
        }
        
        public LoadProfileFieldResponse(ServiceReference.LoadProfileFieldResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/DocufloSDK/Service1")]
    public partial class LoadProfileFieldResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference.ProfileField[] LoadProfileFieldResult;
        
        public LoadProfileFieldResponseBody()
        {
        }
        
        public LoadProfileFieldResponseBody(ServiceReference.ProfileField[] LoadProfileFieldResult)
        {
            this.LoadProfileFieldResult = LoadProfileFieldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    public interface DocufloSDKSoapChannel : ServiceReference.DocufloSDKSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    public partial class DocufloSDKSoapClient : System.ServiceModel.ClientBase<ServiceReference.DocufloSDKSoap>, ServiceReference.DocufloSDKSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DocufloSDKSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(DocufloSDKSoapClient.GetBindingForEndpoint(endpointConfiguration), DocufloSDKSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DocufloSDKSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DocufloSDKSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DocufloSDKSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DocufloSDKSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DocufloSDKSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.ExportResponse> ServiceReference.DocufloSDKSoap.ExportAsync(ServiceReference.ExportRequest request)
        {
            return base.Channel.ExportAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.ExportResponse> ExportAsync(byte[] FileContent, string strFileName, string strProfile, string strFolderName, ServiceReference.ArrayOfString arrProfileValue, string userID)
        {
            ServiceReference.ExportRequest inValue = new ServiceReference.ExportRequest();
            inValue.Body = new ServiceReference.ExportRequestBody();
            inValue.Body.FileContent = FileContent;
            inValue.Body.strFileName = strFileName;
            inValue.Body.strProfile = strProfile;
            inValue.Body.strFolderName = strFolderName;
            inValue.Body.arrProfileValue = arrProfileValue;
            inValue.Body.userID = userID;
            return ((ServiceReference.DocufloSDKSoap)(this)).ExportAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.SearchResponse> ServiceReference.DocufloSDKSoap.SearchAsync(ServiceReference.SearchRequest request)
        {
            return base.Channel.SearchAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.SearchResponse> SearchAsync(string strCriteria)
        {
            ServiceReference.SearchRequest inValue = new ServiceReference.SearchRequest();
            inValue.Body = new ServiceReference.SearchRequestBody();
            inValue.Body.strCriteria = strCriteria;
            return ((ServiceReference.DocufloSDKSoap)(this)).SearchAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.SearchByDocIDResponse> ServiceReference.DocufloSDKSoap.SearchByDocIDAsync(ServiceReference.SearchByDocIDRequest request)
        {
            return base.Channel.SearchByDocIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.SearchByDocIDResponse> SearchByDocIDAsync(int profileID, long docID)
        {
            ServiceReference.SearchByDocIDRequest inValue = new ServiceReference.SearchByDocIDRequest();
            inValue.Body = new ServiceReference.SearchByDocIDRequestBody();
            inValue.Body.profileID = profileID;
            inValue.Body.docID = docID;
            return ((ServiceReference.DocufloSDKSoap)(this)).SearchByDocIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.ProfileSearchResponse> ServiceReference.DocufloSDKSoap.ProfileSearchAsync(ServiceReference.ProfileSearchRequest request)
        {
            return base.Channel.ProfileSearchAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.ProfileSearchResponse> ProfileSearchAsync(string profile_name, ServiceReference.ArrayOfAnyType column_names, ServiceReference.ArrayOfAnyType column_keywords, string error_msg)
        {
            ServiceReference.ProfileSearchRequest inValue = new ServiceReference.ProfileSearchRequest();
            inValue.Body = new ServiceReference.ProfileSearchRequestBody();
            inValue.Body.profile_name = profile_name;
            inValue.Body.column_names = column_names;
            inValue.Body.column_keywords = column_keywords;
            inValue.Body.error_msg = error_msg;
            return ((ServiceReference.DocufloSDKSoap)(this)).ProfileSearchAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.DownloadResponse> ServiceReference.DocufloSDKSoap.DownloadAsync(ServiceReference.DownloadRequest request)
        {
            return base.Channel.DownloadAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.DownloadResponse> DownloadAsync(long VerID, long DocProfileID, short FileType, string FileName, byte[] FileContent)
        {
            ServiceReference.DownloadRequest inValue = new ServiceReference.DownloadRequest();
            inValue.Body = new ServiceReference.DownloadRequestBody();
            inValue.Body.VerID = VerID;
            inValue.Body.DocProfileID = DocProfileID;
            inValue.Body.FileType = FileType;
            inValue.Body.FileName = FileName;
            inValue.Body.FileContent = FileContent;
            return ((ServiceReference.DocufloSDKSoap)(this)).DownloadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.UpdateTargetProfileValueResponse> ServiceReference.DocufloSDKSoap.UpdateTargetProfileValueAsync(ServiceReference.UpdateTargetProfileValueRequest request)
        {
            return base.Channel.UpdateTargetProfileValueAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.UpdateTargetProfileValueResponse> UpdateTargetProfileValueAsync(long docID, string profile_name, string base_column_name, object base_value, string target_column_name, object target_value)
        {
            ServiceReference.UpdateTargetProfileValueRequest inValue = new ServiceReference.UpdateTargetProfileValueRequest();
            inValue.Body = new ServiceReference.UpdateTargetProfileValueRequestBody();
            inValue.Body.docID = docID;
            inValue.Body.profile_name = profile_name;
            inValue.Body.base_column_name = base_column_name;
            inValue.Body.base_value = base_value;
            inValue.Body.target_column_name = target_column_name;
            inValue.Body.target_value = target_value;
            return ((ServiceReference.DocufloSDKSoap)(this)).UpdateTargetProfileValueAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.DeleteDocumentResponse> ServiceReference.DocufloSDKSoap.DeleteDocumentAsync(ServiceReference.DeleteDocumentRequest request)
        {
            return base.Channel.DeleteDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.DeleteDocumentResponse> DeleteDocumentAsync(long docID, long profileID)
        {
            ServiceReference.DeleteDocumentRequest inValue = new ServiceReference.DeleteDocumentRequest();
            inValue.Body = new ServiceReference.DeleteDocumentRequestBody();
            inValue.Body.docID = docID;
            inValue.Body.profileID = profileID;
            return ((ServiceReference.DocufloSDKSoap)(this)).DeleteDocumentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.LoginResponse> ServiceReference.DocufloSDKSoap.LoginAsync(ServiceReference.LoginRequest request)
        {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.LoginResponse> LoginAsync(string userName, string userPassword, string userID)
        {
            ServiceReference.LoginRequest inValue = new ServiceReference.LoginRequest();
            inValue.Body = new ServiceReference.LoginRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.userID = userID;
            return ((ServiceReference.DocufloSDKSoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.LoadProfilesResponse> ServiceReference.DocufloSDKSoap.LoadProfilesAsync(ServiceReference.LoadProfilesRequest request)
        {
            return base.Channel.LoadProfilesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.LoadProfilesResponse> LoadProfilesAsync()
        {
            ServiceReference.LoadProfilesRequest inValue = new ServiceReference.LoadProfilesRequest();
            inValue.Body = new ServiceReference.LoadProfilesRequestBody();
            return ((ServiceReference.DocufloSDKSoap)(this)).LoadProfilesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.LoadProfileFieldResponse> ServiceReference.DocufloSDKSoap.LoadProfileFieldAsync(ServiceReference.LoadProfileFieldRequest request)
        {
            return base.Channel.LoadProfileFieldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.LoadProfileFieldResponse> LoadProfileFieldAsync(int intProfileID)
        {
            ServiceReference.LoadProfileFieldRequest inValue = new ServiceReference.LoadProfileFieldRequest();
            inValue.Body = new ServiceReference.LoadProfileFieldRequestBody();
            inValue.Body.intProfileID = intProfileID;
            return ((ServiceReference.DocufloSDKSoap)(this)).LoadProfileFieldAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DocufloSDKSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.DocufloSDKSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DocufloSDKSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.70.120/e-dmssdk/DocufloSDK.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.DocufloSDKSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.70.120/e-dmssdk/DocufloSDK.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            DocufloSDKSoap,
            
            DocufloSDKSoap12,
        }
    }
}
